# Generated by Django 4.2.3 on 2023-11-23 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodReviewRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_item.foodmodel')),
            ],
        ),
    ]
