# Generated by Django 4.2.3 on 2023-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='restaurant_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
